#!/usr/bin/perl

use strict;
use warnings;
use utf8;

# fix lib paths, some may be relative
BEGIN { # BEGIN RT CMD BOILERPLATE
    require File::Spec;
    require Cwd;
    my @libs = ("lib", "local/lib");
    my $bin_path;

    for my $lib (@libs) {
        unless ( File::Spec->file_name_is_absolute($lib) ) {
            $bin_path ||= ( File::Spec->splitpath(Cwd::abs_path(__FILE__)) )[1];
            $lib = File::Spec->catfile( $bin_path, File::Spec->updir, $lib );
        }
        unshift @INC, $lib;
    }

}

use RT;
use RT::User;

RT::Init();

my $user = RT::User->new( RT->SystemUser );
my ($ret, $msg) = $user->Load("root");

$ret || die "Can't load user: $msg\n";

my $username = $user->Name;
my $password = $ENV{'RT_DEFAULT_PASSWORD'};
die "RT_DEFAULT_PASSWORD environment variable is not set" unless defined $password;

($ret, $msg) = $user->SetPassword($password);
print "\n";

die "Couldn't change password for user $username: $msg\n" unless $ret;

print "Successfully changed password for user $username.\n";
